export const AGREGAR_TITULO = 'AGREGAR_TITULO';

export const AGREGAR_TITULO_EXITO = 'AGREGAR_TITULO_EXITO';

export const COMENZAR_DESCARGA_TITULO = 'COMENZAR_DESCARGA_TITULO';

export const OBTENER_PRODUCTO_TITULO = 'OBTENER_TITULO_ELIMINAR';

export const OBTENER_PRODUCTO_INCREMENTAR = 'OBTENER_PRODUCTO_INCREMENTAR';

export const OBTENER_PRODUCTO_DESINCREMENTAR = 'OBTENER_PRODUCTO_DESINCREMENTAR';

export const COMENZAR_DESCARGA_TITULO_EXITO = 'COMENZAR_DESCARGA_TITULO_EXITO';

export const OBTENER_CONTADOR_ELIMINAR = 'OBTENER_CONTADOR_ELIMINAR';

export const CONTADOR_ELIMINADO_EXITO = 'CONTADOR_ELIMINADO_EXITO';



